version: '3'
services:
  mongodb:
    container_name: mongodb_container
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_volumes:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
volumes:
  mongo_volumes:
